swagger: "2.0"
info:
  title: Hash Server
  description: An exercise in golang
  version: 1.0.0
host: localhost:8080
basePath: /
schemes:
  - http
paths:
  /hash:
    post:
      summary: Hash a new password
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: password
          type: string
          description: password to be hashed
      responses:
        202:
          description: The hashId to use in later retrieving the hash value
          schema:
            type: integer
            example: 12
        400:
          description: Request was invalid

            
  /hash/{hashId}:
    get:
      summary: Returns the hash value for the specified hashId
      produces:
        - application/json
      parameters:
        - in: path
          name: hashId
          required: true
          type: integer
          minimum: 1
          description: an identifier of the hash being requested
      responses:
        200:
          description: the hashed value
          schema:
            type: string
            example: ZEHhWB65gUlzdVwtDQArEyx+KVLzp/aTaRaPlBzYRIFj6vjFdqEb0Q5B8zVKCZ0vKbZPZklJz0Fd7su2A+gf7Q==
        400:
          description: Request was invalid
          schema:
            type: string
            example: Invalid Request HashId "3ff" must be a positive integer
  /stats:
    get:
      summary: Returns some stats
      produces:
        - application/json
      responses:
        200:
          description: some simple request stats
          schema:
            type: object
            properties:
              total:
                type: integer
                description: the number of hashes posted
                example: 1
              average:
                type: integer
                description: TBD - average hashing time (total running ms / requests) 
                example: 123
  /shutdown:
    post:
      summary: initiates a graceful shutdown of the server
      produces:
        - application/json
      responses:
        202:
          description: the shutdown has been acknowledged
